name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}
author: PureGero
api-version: 1.17
website: https://github.com/PureGero/${project.name}
